# Generated by Django 6.0.3 on 2026-04-03 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='model nomi')),
                ('code', models.CharField(blank=True, help_text='Ichki kod / artikul', max_length=50, unique=True, verbose_name='model kodi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10, verbose_name='holat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Mahsulot modeli',
                'verbose_name_plural': 'Mahsulot modellari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ish turi nomi')),
                ('price', models.DecimalField(decimal_places=2, help_text='Joriy birlik narxi', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="narx (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('product_model', models.ForeignKey(help_text='Qaysi mahsulot modeliga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='production.productmodel', verbose_name='mahsulot modeli')),
            ],
            options={
                'verbose_name': 'Ish turi',
                'verbose_name_plural': 'Ish turlari',
                'ordering': ['product_model', 'name'],
                'unique_together': {('product_model', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ish soni')),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text='Ish kiritilgan paytdagi birlik narxi', max_digits=12, verbose_name='narx (snapshot)')),
                ('total_sum', models.DecimalField(decimal_places=2, editable=False, help_text='quantity × price_snapshot — avtomatik hisoblanadi', max_digits=15, verbose_name='jami summa')),
                ('work_date', models.DateField(help_text='Ish bajarilgan sana', verbose_name='ish sanasi')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('manager', models.ForeignKey(help_text='Ishni kiritgan manager', limit_choices_to={'role__in': ['admin', 'manager']}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_work_logs', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to='accounts.worker', verbose_name='ishchi')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to='production.worktype', verbose_name='ish turi')),
            ],
            options={
                'verbose_name': 'Ish jurnali',
                'verbose_name_plural': 'Ish jurnallari',
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['worker', 'work_date'], name='production__worker__84e2e7_idx'), models.Index(fields=['work_type', 'work_date'], name='production__work_ty_2d529a_idx'), models.Index(fields=['manager', 'work_date'], name='production__manager_3e2f48_idx')],
            },
        ),
    ]
