# Generated by Django 6.0.3 on 2026-04-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='production.productmodel')),
            ],
            options={
                'verbose_name': 'Model rasmi',
                'verbose_name_plural': 'Model rasmlari',
                'ordering': ['created_at'],
            },
        ),
    ]
