# Generated by Django 6.0.3 on 2026-04-03 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Berilgan avans summasi', max_digits=12, verbose_name='summa')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='sana')),
                ('description', models.TextField(blank=True, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_advances', to=settings.AUTH_USER_MODEL, verbose_name='menejer (bergan xodim)')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='accounts.worker', verbose_name='ishchi')),
            ],
            options={
                'verbose_name': 'Avans',
                'verbose_name_plural': 'Avanslar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='oy')),
                ('year', models.PositiveIntegerField(verbose_name='yil')),
                ('total_work_sum', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='jami ishlagan summasi')),
                ('total_advance_sum', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='jami olgan avansi')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, help_text="Xodimning qo'liga tegadigan(sof) oylik miqdori", max_digits=15, verbose_name="to'lanadigan summa")),
                ('is_paid', models.BooleanField(default=False, verbose_name="to'landimi?")),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='hisob-kitob yopilgan vaqt')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='accounts.worker', verbose_name='ishchi')),
            ],
            options={
                'verbose_name': 'Oylik hisob-kitob',
                'verbose_name_plural': 'Oylik hisob-kitoblar',
                'ordering': ['-year', '-month'],
                'unique_together': {('worker', 'month', 'year')},
            },
        ),
    ]
