# Generated by Django 6.0.3 on 2026-04-03 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_advancepayment_salarypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('record_id', models.IntegerField(verbose_name='Yozuv ID')),
                ('action', models.CharField(choices=[('CREATE', 'Yaratish'), ('UPDATE', 'Tahrirlash'), ('DELETE', "O'chirish")], max_length=15, verbose_name='Amaliyot Turi')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Eski Qiymatlar')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Yangi Qiymatlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qayd Vaqti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi Shaxs')),
            ],
            options={
                'verbose_name': 'Audit Logi',
                'verbose_name_plural': 'Audit Loglari',
                'ordering': ['-created_at'],
            },
        ),
    ]
