# Generated by Django 6.0.3 on 2026-04-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Nofaol ishchilar lookup va statistikadan chiqariladi', verbose_name='faolmi?'),
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('tikuvchi', 'Tikuvchi'), ('bichuvchi', 'Bichuvchi'), ('qadoqchi', 'Qadoqchi'), ('dazmolchi', 'Dazmolchi'), ('boshqa', 'Boshqa')], default='boshqa', max_length=15, verbose_name='lavozim'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Bo'sh qoldirilsa avtomatik generatsiya bo'ladi (W-001, W-002, ...)", max_length=20, unique=True, verbose_name='ishchi kodi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('on_leave', "Ta'tilda")], default='active', max_length=10, verbose_name='ish holati'),
        ),
    ]
