# Generated by Django 6.0.3 on 2026-04-06 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_worker_is_active_worker_role_alter_worker_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name="o'chirilganmi (arxivdami)?"),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_payments', to='accounts.worker', verbose_name='ishchi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='code',
            field=models.CharField(db_index=True, help_text='Ishchi uchun unikal identifikatsiya kodi', max_length=20, unique=True, verbose_name='ishchi kodi'),
        ),
    ]
