# Generated by Django 6.0.3 on 2026-04-03 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, help_text='Ishlab chiqarish partiyasi identifikatori', max_length=50, verbose_name='partiya raqami')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='miqdor')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('fabric_type', models.CharField(help_text='Masalan: trikotaj, paxtali, sintetik', max_length=200, verbose_name='gazlama turi')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='rang')),
                ('roll_count', models.PositiveIntegerField(default=1, verbose_name='rulonlar soni')),
                ('status', models.CharField(choices=[('received', 'Qabul qilingan'), ('in_use', 'Ishlatilmoqda'), ('exhausted', 'Tugagan')], default='received', max_length=10, verbose_name='holat')),
                ('received_date', models.DateField(verbose_name='qabul qilingan sana')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productmodel', verbose_name='mahsulot modeli')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_sklad_items', to=settings.AUTH_USER_MODEL, verbose_name='qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Sklad (Gazlama)',
                'verbose_name_plural': 'Sklad (Gazlamalar)',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='Bichuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, help_text='Ishlab chiqarish partiyasi identifikatori', max_length=50, verbose_name='partiya raqami')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='miqdor')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('cut_date', models.DateField(verbose_name='bichilgan sana')),
                ('defect_count', models.PositiveIntegerField(default=0, help_text='Bichish jarayonida aniqlangan nuqsonli donalar soni', verbose_name='nuqsonli dona')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan')], default='pending', max_length=12, verbose_name='holat')),
                ('cut_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_bichuv_items', to=settings.AUTH_USER_MODEL, verbose_name='bichuvchi')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productmodel', verbose_name='mahsulot modeli')),
                ('sklad', models.ForeignKey(help_text='Qaysi sklad partiyasidan bichilgan', on_delete=django.db.models.deletion.PROTECT, related_name='bichuv_items', to='inventory.sklad', verbose_name='sklad partiyasi')),
            ],
            options={
                'verbose_name': 'Bichuv',
                'verbose_name_plural': 'Bichuvlar',
                'ordering': ['-cut_date'],
            },
        ),
        migrations.CreateModel(
            name='Upakovka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, help_text='Ishlab chiqarish partiyasi identifikatori', max_length=50, verbose_name='partiya raqami')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='miqdor')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('pack_date', models.DateField(verbose_name='qadoqlangan sana')),
                ('box_count', models.PositiveIntegerField(default=1, help_text='Nechta qutiga joylangan', verbose_name='quti soni')),
                ('defect_count', models.PositiveIntegerField(default=0, verbose_name='nuqsonli dona')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('packed', 'Qadoqlangan'), ('shipped', "Jo'natilgan")], default='pending', max_length=10, verbose_name='holat')),
                ('bichuv', models.ForeignKey(help_text='Qaysi bichuv partiyasidan kelgan', on_delete=django.db.models.deletion.PROTECT, related_name='upakovka_items', to='inventory.bichuv', verbose_name='bichuv partiyasi')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_upakovka_items', to=settings.AUTH_USER_MODEL, verbose_name='qadoqlovchi')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productmodel', verbose_name='mahsulot modeli')),
            ],
            options={
                'verbose_name': 'Upakovka',
                'verbose_name_plural': 'Upakovkalar',
                'ordering': ['-pack_date'],
            },
        ),
        migrations.AddIndex(
            model_name='sklad',
            index=models.Index(fields=['batch_number'], name='inventory_s_batch_n_daeccb_idx'),
        ),
        migrations.AddIndex(
            model_name='sklad',
            index=models.Index(fields=['status'], name='inventory_s_status_4470ba_idx'),
        ),
        migrations.AddIndex(
            model_name='bichuv',
            index=models.Index(fields=['batch_number'], name='inventory_b_batch_n_162208_idx'),
        ),
        migrations.AddIndex(
            model_name='bichuv',
            index=models.Index(fields=['status'], name='inventory_b_status_670007_idx'),
        ),
        migrations.AddIndex(
            model_name='upakovka',
            index=models.Index(fields=['batch_number'], name='inventory_u_batch_n_e9abfe_idx'),
        ),
        migrations.AddIndex(
            model_name='upakovka',
            index=models.Index(fields=['status'], name='inventory_u_status_071b2f_idx'),
        ),
    ]
