# Generated by Django 6.0.3 on 2026-04-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bichuv',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Bichilgan jami qismlar og'irligi", max_digits=10, verbose_name="og'irligi (kg)"),
        ),
    ]
