# Generated by Django 6.0.3 on 2026-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bichuv_weight_kg'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_weaver', models.CharField(max_length=200, verbose_name="to'quvchi")),
                ('supplier_dyer', models.CharField(max_length=200, verbose_name="bo'yoqchi")),
                ('batch_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='partiya raqami')),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='jami kg')),
                ('roll_count', models.PositiveIntegerField(verbose_name='rulonlar soni')),
                ('fabric_image', models.ImageField(blank=True, null=True, upload_to='fabrics/%Y/%m/', verbose_name='gazlama rasmi')),
                ('waste_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='isrof kg')),
                ('waste_type', models.CharField(blank=True, choices=[('defect', 'Zavod braki (Defect)'), ('cutting', 'Qiyqindi (Cutting waste)'), ('other', 'Boshqa (Other)')], max_length=20, null=True, verbose_name='isrof turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_models', models.ManyToManyField(related_name='fabric_batches', to='production.productmodel', verbose_name='biriktirilgan modellar')),
            ],
            options={
                'verbose_name': 'Fabric Inventory',
                'verbose_name_plural': 'Fabric Inventories',
            },
        ),
    ]
