# Generated by Django 6.0.3 on 2026-04-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fabricinventory'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricinventory',
            name='assigned_models',
            field=models.ManyToManyField(blank=True, related_name='fabric_batches', to='production.productmodel', verbose_name='biriktirilgan modellar'),
        ),
    ]
