# Generated by Django 6.0.3 on 2026-04-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_fabricinventory_assigned_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricinventory',
            name='total_kg',
            field=models.PositiveIntegerField(verbose_name='jami kg'),
        ),
        migrations.AlterField(
            model_name='fabricinventory',
            name='waste_kg',
            field=models.PositiveIntegerField(default=0, verbose_name='isrof kg'),
        ),
    ]
