# Generated by Django 6.0.3 on 2026-04-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_fabricinventory_total_kg_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(default='Gazlama', max_length=100, verbose_name='xom-ashyo turi')),
                ('min_kg', models.PositiveIntegerField(verbose_name='minimal chegara (kg)')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='production.productmodel', verbose_name='model')),
            ],
            options={
                'verbose_name': 'Zaxira chegarasi',
                'verbose_name_plural': 'Zaxira chegaralari',
            },
        ),
    ]
