# Generated by Django 6.0.3 on 2026-04-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockthreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricinventory',
            name='supplier_dyer',
            field=models.CharField(blank=True, max_length=200, verbose_name="bo'yoqchi"),
        ),
        migrations.AlterField(
            model_name='fabricinventory',
            name='supplier_weaver',
            field=models.CharField(blank=True, max_length=200, verbose_name="to'quvchi"),
        ),
    ]
