# Generated by Django 6.0.3 on 2026-04-08 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_fabricinventory_supplier_dyer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.PositiveIntegerField(verbose_name='brak kg')),
                ('brak_type', models.CharField(choices=[('tovuvchi', "To'quvchi braki"), ('bichuvchi', 'Bichuvchi braki'), ('aralash', 'Ikkalasi (aralash)')], max_length=20, verbose_name='brak turi')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='kim kiritdi')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brak_logs', to='inventory.fabricinventory', verbose_name='partiya')),
            ],
            options={
                'verbose_name': 'Brak logi',
                'verbose_name_plural': 'Brak loglari',
                'ordering': ['-created_at'],
            },
        ),
    ]
