# Generated by Django 6.0.3 on 2026-04-10 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_braklog'),
        ('production', '0002_productmodelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BichuvChiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kesim_number', models.PositiveIntegerField(help_text='Bir xil partiya+model uchun avtomatik oshib boradi', verbose_name='kesim raqami')),
                ('ish_soni', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ish soni')),
                ('beka_kg', models.PositiveIntegerField(default=0, help_text='Gazlamani bichganidan chiqqan ortiqcha qoldiq', verbose_name='beka (kg)')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bichuv_chiqim_items', to='inventory.fabricinventory', verbose_name='sklad partiyasi')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productmodel', verbose_name='mahsulot modeli')),
            ],
            options={
                'verbose_name': 'Bichuv Chiqim',
                'verbose_name_plural': 'Bichuv Chiqimlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BichuvKirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="og'irligi (kg)")),
                ('roll_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='rulonlar soni')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bichuv_kirim_items', to='inventory.fabricinventory', verbose_name='sklad partiyasi')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productmodel', verbose_name='mahsulot modeli')),
            ],
            options={
                'verbose_name': 'Bichuv Kirim',
                'verbose_name_plural': 'Bichuv Kirimlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
