name: Auto Deploy to Ubuntu VPS (SelenTextile)

on:
  push:
    branches:
      - main # Asosiy shoh serverga tortilsa

jobs:
  deploy:
    name: Yig'ish va Yuborish (CI/CD)
    runs-on: ubuntu-latest

    steps:
    - name: Loyihani olish
      uses: actions/checkout@v3

    - name: Serverga ulanish (SSH) va Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }} # GitHub settings qismidan o'rnatiladi
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # 1. Loyiha papkasiga kirib borish
          cd /var/www/selen-textile
          
          # 2. Yangi kodlarni (pushni) Git'dan tortib olish
          git pull origin main
          
          # 3. Yopilgan env va migratsiyalarni qayta tuzib tushirish
          docker-compose up --build -d
          
          # Keraksiz chiqqan "dangling" docker axlatlarini asrab qolmasdan o'chirish (Xotira tozaligi uchun)
          docker image prune -f
